#!/usr/bin/env python -2
# NR=100
# NC=100
# X_sle; Ysel
# for each_dict in dicts:
#     for i in range(NR):
#         for j in range(NC):
#             if each_dict["R"]=Rd[i] and each_dict["L"]=Ld[j]:
#                 arry[i][j][each_dict["Loop"]]+=1
import sqlite3
conn = sqlite3.connect("example.db")
c = conn.cursor()

# Create table
c.execute('''CREATE TABLE stocks
             (reg text, field text, cnt real, side real, lane real)''')

# Insert a row of data
array=[]
for i in range(2):
    for j in range(8):
        array.append(('A','a1',i+j,i,j))
print(array)
c.executemany("INSERT INTO stocks VALUES (?,?,?,?,?)",array)
# Save (commit) the changes
conn.commit()

t=(3,)
for row in c.execute('SELECT * FROM stocks WHERE lane=?', t):
    print(row)

conn.close()
